### ISSUE TITLE
数据库单节点

### ISSUE THREAD

**Issue by 729234500** [wormsleep/etl#3]
database-subnode-name
单节点数据库这个该如何表示？？？？？
有没有实例提供参考

**Comment by 729234500** [comment]
[ETL]2017-06-05 13:38:12,551 DEBUG BasicResourcePool.awaitAvailable - awaitAvailable(): [unknown]
[ETL]2017-06-05 13:38:12,552 DEBUG BasicResourcePool.trace - trace com.mchange.v2.resourcepool.BasicResourcePool@54d9d12d [managed: 0, unused: 0, excluded: 0]
[ETL]2017-06-05 13:38:12,554 DEBUG BasicResourcePool.run - An exception occurred while acquiring a poolable resource. Will retry.
java.lang.NullPointerException
	at com.mysql.fabric.jdbc.FabricMySQLDriver.parseFabricURL(FabricMySQLDriver.java:96)
	at com.mysql.fabric.jdbc.FabricMySQLDriver.acceptsURL(FabricMySQLDriver.java:92)
	at java.sql.DriverManager.getDriver(DriverManager.java:299)
	at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:223)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:119)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:143)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:132)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)
[ETL]2017-06-05 13:38:12,553 DEBUG BasicResourcePool.run - An exception occurred while acquiring a poolable resource. Will retry.
java.lang.NullPointerException
	at com.mysql.fabric.jdbc.FabricMySQLDriver.parseFabricURL(FabricMySQLDriver.java:96)
	at com.mysql.fabric.jdbc.FabricMySQLDriver.acceptsURL(FabricMySQLDriver.java:92)
	at java.sql.DriverManager.getDriver(DriverManager.java:299)
	at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:223)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:119)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:143)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:132)

**Comment by 729234500** [comment]
@wormsleep 请问这个是什么错误？
